name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest

    steps:     
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
      - name: Check out code
        uses: actions/checkout@v3.3.0
        
      - name: Remove nuget.config
        uses: JesseTG/rm@v1.0.3
        with:
          path: nuget.config
          
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.203'
          
      - name: Display dotnet version   
        shell: bash
        run: |
            dotnet format --version

      - name: Run dotnet format
        shell: bash
        run: |
            dotnet format --verify-no-changes --verbosity detailed
